import type { ThemeConfig, ThemeId } from './theme.types';

/**
 * Theme Configuration
 *
 * Central config for all preset themes.
 * All colors are explicit Tailwind classes for theme isolation.
 */
export const THEMES: Record<ThemeId, ThemeConfig> = {
  default: {
    id: 'default',
    name: 'Clean Light',
    category: 'solid',
    previewClass: 'bg-white border-neutral-200 text-neutral-900',
    colors: {
      background: 'bg-white',
      textPrimary: 'text-neutral-900',
      textSecondary: 'text-neutral-600',
      elementBg: 'bg-black/5',
      elementBorder: 'border-black/10',
      elementRing: 'ring-black/5',
      buttonBg: 'bg-white',
      buttonBorder: 'border-neutral-200',
      buttonText: 'text-neutral-900',
      buttonHoverBg: 'hover:bg-neutral-50',
      buttonHoverBorder: 'hover:border-neutral-300',
      outlineBorder: 'border-black/20',
      outlineText: 'text-neutral-900',
      outlineHoverBg: 'hover:bg-black/5',
      footerBg: 'bg-black/5',
      footerBorder: 'border-black/10',
      footerText: 'text-neutral-600',
      footerBrandText: 'text-neutral-900',
    },
  },

  dark: {
    id: 'dark',
    name: 'Deep Dark',
    category: 'solid',
    previewClass: 'bg-neutral-950 border-neutral-800 text-white',
    colors: {
      background: 'bg-neutral-950',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  gradient: {
    id: 'gradient',
    name: 'Cosmic Purple',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-indigo-600 via-purple-700 to-slate-900 border-transparent text-white',
    colors: {
      background:
        'bg-gradient-to-br from-indigo-600 via-purple-700 to-slate-950',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  peach: {
    id: 'peach',
    name: 'Peach Sunset',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-orange-400 via-rose-500 to-pink-600 border-transparent text-white',
    colors: {
      background: 'bg-gradient-to-br from-orange-400 via-rose-500 to-pink-600',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  deepsea: {
    id: 'deepsea',
    name: 'Deep Sea',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-teal-500 via-blue-700 to-slate-900 border-transparent text-white',
    colors: {
      background: 'bg-gradient-to-br from-teal-500 via-blue-700 to-slate-900',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald Lake',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-emerald-500 via-green-700 to-teal-900 border-transparent text-white',
    colors: {
      background:
        'bg-gradient-to-br from-emerald-500 via-green-700 to-teal-900',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  lavender: {
    id: 'lavender',
    name: 'Soft Lavender',
    category: 'soft',
    previewClass:
      'bg-gradient-to-br from-violet-200 via-purple-300 to-fuchsia-400 border-transparent text-neutral-800',
    colors: {
      background:
        'bg-gradient-to-br from-violet-200 via-purple-300 to-fuchsia-400',
      textPrimary: 'text-neutral-900',
      textSecondary: 'text-neutral-600',
      elementBg: 'bg-black/5',
      elementBorder: 'border-black/10',
      elementRing: 'ring-black/5',
      buttonBg: 'bg-black/5',
      buttonBorder: 'border-black/10',
      buttonText: 'text-neutral-900',
      buttonHoverBg: 'hover:bg-black/10',
      buttonHoverBorder: 'hover:border-black/20',
      outlineBorder: 'border-black/20',
      outlineText: 'text-neutral-900',
      outlineHoverBg: 'hover:bg-black/5',
      footerBg: 'bg-black/5',
      footerBorder: 'border-black/10',
      footerText: 'text-neutral-600',
      footerBrandText: 'text-neutral-900',
    },
  },

  latte: {
    id: 'latte',
    name: 'Creamy Latte',
    category: 'soft',
    previewClass:
      'bg-gradient-to-br from-orange-50 via-amber-50 to-stone-200 border-transparent text-neutral-800',
    colors: {
      background: 'bg-gradient-to-br from-orange-50 via-amber-50 to-stone-200',
      textPrimary: 'text-neutral-900',
      textSecondary: 'text-neutral-600',
      elementBg: 'bg-black/5',
      elementBorder: 'border-black/10',
      elementRing: 'ring-black/5',
      buttonBg: 'bg-black/5',
      buttonBorder: 'border-black/10',
      buttonText: 'text-neutral-900',
      buttonHoverBg: 'hover:bg-black/10',
      buttonHoverBorder: 'hover:border-black/20',
      outlineBorder: 'border-black/20',
      outlineText: 'text-neutral-900',
      outlineHoverBg: 'hover:bg-black/5',
      footerBg: 'bg-black/5',
      footerBorder: 'border-black/10',
      footerText: 'text-neutral-600',
      footerBrandText: 'text-neutral-900',
    },
  },

  midnight: {
    id: 'midnight',
    name: 'Midnight Blue',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-950 border-transparent text-white',
    colors: {
      background: 'bg-gradient-to-br from-slate-900 via-blue-900 to-indigo-950',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  sunset: {
    id: 'sunset',
    name: 'Sunset Gold',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-amber-400 via-orange-500 to-red-600 border-transparent text-white',
    colors: {
      background: 'bg-gradient-to-br from-amber-400 via-orange-500 to-red-600',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },

  rosegold: {
    id: 'rosegold',
    name: 'Rose Gold',
    category: 'soft',
    previewClass:
      'bg-gradient-to-br from-rose-300 via-pink-400 to-fuchsia-600 border-transparent text-neutral-800',
    colors: {
      background: 'bg-gradient-to-br from-rose-300 via-pink-400 to-fuchsia-600',
      textPrimary: 'text-neutral-900',
      textSecondary: 'text-neutral-600',
      elementBg: 'bg-black/5',
      elementBorder: 'border-black/10',
      elementRing: 'ring-black/5',
      buttonBg: 'bg-black/5',
      buttonBorder: 'border-black/10',
      buttonText: 'text-neutral-900',
      buttonHoverBg: 'hover:bg-black/10',
      buttonHoverBorder: 'hover:border-black/20',
      outlineBorder: 'border-black/20',
      outlineText: 'text-neutral-900',
      outlineHoverBg: 'hover:bg-black/5',
      footerBg: 'bg-black/5',
      footerBorder: 'border-black/10',
      footerText: 'text-neutral-600',
      footerBrandText: 'text-neutral-900',
    },
  },

  ocean: {
    id: 'ocean',
    name: 'Ocean Breeze',
    category: 'soft',
    previewClass:
      'bg-gradient-to-br from-sky-400 via-cyan-500 to-blue-700 border-transparent text-neutral-800',
    colors: {
      background: 'bg-gradient-to-br from-sky-400 via-cyan-500 to-blue-700',
      textPrimary: 'text-neutral-900',
      textSecondary: 'text-neutral-600',
      elementBg: 'bg-black/5',
      elementBorder: 'border-black/10',
      elementRing: 'ring-black/5',
      buttonBg: 'bg-black/5',
      buttonBorder: 'border-black/10',
      buttonText: 'text-neutral-900',
      buttonHoverBg: 'hover:bg-black/10',
      buttonHoverBorder: 'hover:border-black/20',
      outlineBorder: 'border-black/20',
      outlineText: 'text-neutral-900',
      outlineHoverBg: 'hover:bg-black/5',
      footerBg: 'bg-black/5',
      footerBorder: 'border-black/10',
      footerText: 'text-neutral-600',
      footerBrandText: 'text-neutral-900',
    },
  },

  charcoal: {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'gradient',
    previewClass:
      'bg-gradient-to-br from-zinc-800 via-neutral-900 to-stone-950 border-transparent text-white',
    colors: {
      background:
        'bg-gradient-to-br from-zinc-800 via-neutral-900 to-stone-950',
      textPrimary: 'text-white',
      textSecondary: 'text-white/80',
      elementBg: 'bg-white/10',
      elementBorder: 'border-white/20',
      elementRing: 'ring-white/20',
      buttonBg: 'bg-white/10',
      buttonBorder: 'border-white/20',
      buttonText: 'text-white',
      buttonHoverBg: 'hover:bg-white/20',
      buttonHoverBorder: 'hover:border-white/30',
      outlineBorder: 'border-white/30',
      outlineText: 'text-white',
      outlineHoverBg: 'hover:bg-white/10',
      footerBg: 'bg-white/10',
      footerBorder: 'border-white/20',
      footerText: 'text-white/70',
      footerBrandText: 'text-white',
    },
  },
};

/** List of all available themes for iteration */
export const THEME_LIST = Object.values(THEMES);

/** Default theme ID */
export const DEFAULT_THEME_ID = 'default' as const;
