// Supabase Database Types
// NOTE: Replace this with types generated by Supabase CLI:
// npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          display_name: string | null;
          bio: string | null;
          avatar_url: string | null;
          theme_name: string | null;
          button_style: string | null;
          button_shape: string | null;
          default_currency: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          username: string;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          theme_name?: string | null;
          button_style?: string | null;
          button_shape?: string | null;
          default_currency?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          display_name?: string | null;
          bio?: string | null;
          avatar_url?: string | null;
          theme_name?: string | null;
          button_style?: string | null;
          button_shape?: string | null;
          default_currency?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      links: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          url: string;
          sort_order: number;
          is_active: boolean;
          clicks: number;
          last_clicked_at: string | null;
          created_at: string;
          short_id: number | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          url: string;
          sort_order?: number;
          is_active?: boolean;
          clicks?: number;
          last_clicked_at?: string | null;
          created_at?: string;
          short_id?: number;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          url?: string;
          sort_order?: number;
          is_active?: boolean;
          clicks?: number;
          last_clicked_at?: string | null;
          created_at?: string;
          short_id?: number;
        };
        Relationships: [
          {
            foreignKeyName: 'links_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      link_events: {
        Row: {
          id: string;
          link_id: string;
          created_at: string;
          user_agent: string | null;
          country: string | null;
          city: string | null;
          referer: string | null;
        };
        Insert: {
          id?: string;
          link_id: string;
          created_at?: string;
          user_agent?: string | null;
          country?: string | null;
          city?: string | null;
          referer?: string | null;
        };
        Update: {
          id?: string;
          link_id?: string;
          created_at?: string;
          user_agent?: string | null;
          country?: string | null;
          city?: string | null;
          referer?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'link_events_link_id_fkey';
            columns: ['link_id'];
            isOneToOne: false;
            referencedRelation: 'links';
            referencedColumns: ['id'];
          },
        ];
      };
      profile_events: {
        Row: {
          id: string;
          profile_id: string;
          created_at: string;
          user_agent: string | null;
          country: string | null;
          city: string | null;
          referer: string | null;
          device_type: string | null;
        };
        Insert: {
          id?: string;
          profile_id: string;
          created_at?: string;
          user_agent?: string | null;
          country?: string | null;
          city?: string | null;
          referer?: string | null;
          device_type?: string | null;
        };
        Update: {
          id?: string;
          profile_id?: string;
          created_at?: string;
          user_agent?: string | null;
          country?: string | null;
          city?: string | null;
          referer?: string | null;
          device_type?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'profile_events_profile_id_fkey';
            columns: ['profile_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      cashflows: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          is_public: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          is_public?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          is_public?: boolean;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'cashflows_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      cashflow_shares: {
        Row: {
          id: string;
          cashflow_id: string;
          email: string;
          role: 'read' | 'edit';
          created_at: string;
          is_included_in_totals: boolean;
          created_via_public_access: boolean;
          is_pinned: boolean;
        };
        Insert: {
          id?: string;
          cashflow_id: string;
          email: string;
          role?: 'read' | 'edit';
          created_at?: string;
          is_included_in_totals?: boolean;
          created_via_public_access?: boolean;
          is_pinned?: boolean;
        };
        Update: {
          id?: string;
          cashflow_id?: string;
          email?: string;
          role?: 'read' | 'edit';
          created_at?: string;
          is_included_in_totals?: boolean;
          created_via_public_access?: boolean;
          is_pinned?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: 'cashflow_shares_cashflow_id_fkey';
            columns: ['cashflow_id'];
            isOneToOne: false;
            referencedRelation: 'cashflows';
            referencedColumns: ['id'];
          },
        ];
      };
      cashflow_entries: {
        Row: {
          id: string;
          cashflow_id: string;
          description: string;
          amount: number;
          type: 'income' | 'expense';
          date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          cashflow_id: string;
          description: string;
          amount: number;
          type: 'income' | 'expense';
          date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          cashflow_id?: string;
          description?: string;
          amount?: number;
          type?: 'income' | 'expense';
          date?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'cashflow_entries_cashflow_id_fkey';
            columns: ['cashflow_id'];
            isOneToOne: false;
            referencedRelation: 'cashflows';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {
      cashflow_summaries: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          created_at: string;
          entry_count: number;
          income: number;
          expense: number;
          balance: number;
        };
        Relationships: [];
      };
    };
    Functions: {
      increment_link_click: {
        Args: { link_id: string };
        Returns: undefined;
      };
      get_analytics_chart_data: {
        Args: {
          p_link_ids: string[];
          p_start_date: string | null;
          p_bucket_interval: string;
        };
        Returns: { bucket: string | null; click_count: number }[];
      };
      get_top_referers: {
        Args: {
          p_link_ids: string[];
          p_start_date: string | null;
          p_limit: number;
        };
        Returns: { referer_domain: string; click_count: number }[];
      };
      get_next_short_id: {
        Args: { p_user_id: string };
        Returns: number;
      };
      reorder_links: {
        Args: { p_link_ids: string[] };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Helper types for easier access
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Link = Database['public']['Tables']['links']['Row'];
export type Cashflow = Database['public']['Tables']['cashflows']['Row'];
export type CashflowEntry =
  Database['public']['Tables']['cashflow_entries']['Row'];
export type InsertProfile = Database['public']['Tables']['profiles']['Insert'];
export type InsertLink = Database['public']['Tables']['links']['Insert'];
export type InsertCashflow =
  Database['public']['Tables']['cashflows']['Insert'];
export type InsertCashflowEntry =
  Database['public']['Tables']['cashflow_entries']['Insert'];
export type UpdateProfile = Database['public']['Tables']['profiles']['Update'];
export type UpdateLink = Database['public']['Tables']['links']['Update'];
export type UpdateCashflow =
  Database['public']['Tables']['cashflows']['Update'];
export type UpdateCashflowEntry =
  Database['public']['Tables']['cashflow_entries']['Update'];
